"""EO-EA canonical bridge denominator execution closure.

EO-EA observes bridge execution generated by the canonical runtime and refuses
to count certification-harness or direct executor traces as production
coverage.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from enum import Enum
import hashlib
import json
from pathlib import Path
from typing import Any

from argos.foundation.contracts import utc_timestamp

from .canonical_bridge_fabric import (
    BridgeImplementationStatus,
    BridgeRequirementClass,
    BridgeResultStatus,
    BridgeTransferClass,
    CanonicalBridgeDefinition,
    default_bridge_definitions,
)
from .canonical_enterprise_runtime import CanonicalEnterpriseRuntime
from .trace_equivalence import TraceEquivalenceLevel


EO_EA_VERSION = "EO-EA.1"
PRIOR_AUDIT_COMMIT = "0aeec77fb6eb0768ffbaaa313725dc6d49ca31ca"
PRIOR_REQUIRED_COUNT = 30


class BridgeExecutionEvidenceClass(str, Enum):
    DECLARED = "DECLARED"
    STATICALLY_VALIDATED = "STATICALLY_VALIDATED"
    CONTRACT_EXECUTED = "CONTRACT_EXECUTED"
    INTEGRATION_EXECUTED = "INTEGRATION_EXECUTED"
    CANONICAL_RUNTIME_EXECUTED = "CANONICAL_RUNTIME_EXECUTED"
    EXTERNAL_OPERATIONALLY_EXECUTED = "EXTERNAL_OPERATIONALLY_EXECUTED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    UNEXECUTED = "UNEXECUTED"
    RETIRED = "RETIRED"
    BLOCKED = "BLOCKED"


@dataclass(frozen=True)
class BridgeTruthModel:
    bridge_id: str
    source_component: str
    destination_component: str
    source_component_classification: str
    destination_component_classification: str
    workflow_type: str
    artifact_type: str
    input_schema: str
    output_schema: str
    ownership_semantics: str
    information_delivery_semantics: str
    source_authority: str
    destination_authority: str
    token_requirement: str
    proof_domains: tuple[str, ...]
    activation_conditions: tuple[str, ...]
    acceptance_conditions: tuple[str, ...]
    rejection_conditions: tuple[str, ...]
    persistence_requirements: str
    audit_requirements: str
    retry_rules: str
    timeout_rules: str
    idempotency_rules: str
    recovery_rules: str
    dormancy_implications: str
    failure_severity: str
    readiness_impact: str
    schema_version: str = EO_EA_VERSION


@dataclass(frozen=True)
class EOEABridgeCoverageRow:
    bridge_id: str
    group: str
    source: str
    destination: str
    classification: str
    required_status: str
    implementation_status: str
    source_artifact: str
    source_authority: str
    provenance_status: str
    proof_domain: str
    canonical_execution_count: int
    successful_execution_count: int
    rejection_count: int
    failure_count: int
    recovery_count: int
    idempotency_count: int
    highest_trace_equivalence_level: str
    destination_acceptance_evidence: str
    lifecycle_evidence: str
    dormancy_evidence: str
    final_status: str
    blocker: str
    schema_version: str = EO_EA_VERSION


def execute_eoea_certification(repository_commit: str = "WORKTREE") -> dict[str, Any]:
    definitions = default_bridge_definitions()
    required = tuple(item for item in definitions if item.requirement_class == BridgeRequirementClass.REQUIRED_PRODUCTION)
    excluded = tuple(item for item in definitions if item.requirement_class != BridgeRequirementClass.REQUIRED_PRODUCTION)
    starting = _starting_denominator(definitions)
    runtime = CanonicalEnterpriseRuntime()
    runtime.start()
    campaign = runtime.run_canonical_bridge_denominator_campaign()
    runtime.halt(reason="EO-EA bounded canonical bridge campaign complete.")
    campaign_rows = {str(item["bridgeId"]): item for item in campaign["bridgeResults"]}
    truth_models = tuple(_truth_model(item) for item in definitions)
    matrix = tuple(_coverage_row(item, campaign_rows.get(item.bridge_id, {})) for item in required)
    coverage = _coverage_summary(matrix, excluded)
    blocked = tuple(row for row in matrix if row.final_status == BridgeExecutionEvidenceClass.BLOCKED.value)
    failed = tuple(row for row in matrix if row.final_status == BridgeExecutionEvidenceClass.FAILED.value)
    unexecuted = tuple(row for row in matrix if row.final_status == BridgeExecutionEvidenceClass.UNEXECUTED.value)
    unsafe = tuple(row for row in matrix if row.final_status in {BridgeExecutionEvidenceClass.FAILED.value, BridgeExecutionEvidenceClass.UNEXECUTED.value})
    verdict = "FAIL" if unsafe else ("PASS" if not blocked and coverage["canonical_runtime_executed"] == len(required) else "INCOMPLETE")
    certification = {
        "orderId": "EO-EA",
        "schemaVersion": EO_EA_VERSION,
        "repositoryCommit": repository_commit,
        "priorAuditCommit": PRIOR_AUDIT_COMMIT,
        "verdict": verdict,
        "readiness": "Canonical runtime bridge campaign implemented; authority/provenance/recovery dependencies remain blocked." if verdict == "INCOMPLETE" else ("Bridge denominator execution failed." if verdict == "FAIL" else "Bridge denominator executed."),
        "startingRequiredCount": starting["required_count"],
        "currentRequiredCount": len(required),
        "canonicalRuntimeExecuted": coverage["canonical_runtime_executed"],
        "blockedCount": len(blocked),
        "failedCount": len(failed),
        "unexecutedCount": len(unexecuted),
        "evidenceHash": _stable_hash((matrix, coverage, repository_commit)),
        "timestampUtc": utc_timestamp(),
    }
    return {
        "candidate_identity": {"repositoryCommit": repository_commit, "workingTreeState": "captured by generator manifest", "priorAuditCommit": PRIOR_AUDIT_COMMIT},
        "authoritative_bridge_inventory": tuple(asdict(item) for item in definitions),
        "bridge_denominator": {
            "priorRequiredCount": PRIOR_REQUIRED_COUNT,
            "currentRequiredCount": len(required),
            "excludedCount": len(excluded),
            "addedBridges": (),
            "removedBridges": (),
            "reclassifiedBridges": tuple({"bridgeId": item.bridge_id, "classification": item.requirement_class.value, "disposition": "excluded from internal production denominator"} for item in excluded),
            "retiredBridges": tuple(item.bridge_id for item in excluded if item.requirement_class == BridgeRequirementClass.RETIRED),
            "reconciliation": "Current canonical fabric has 30 registered bridges; 29 are required production and BRIDGE-REPLAY-LAB-001 is replay-only.",
        },
        "bridge_classification": coverage,
        "bridge_truth_models": tuple(asdict(item) for item in truth_models),
        "runtime_trigger_inventory": tuple(_trigger(item) for item in definitions),
        "source_artifact_validation": tuple(_source_validation(row) for row in matrix),
        "destination_acceptance_validation": tuple(_acceptance_validation(row) for row in matrix),
        "ownership_transfer_validation": tuple(_ownership_validation(row) for row in matrix if row.classification == BridgeTransferClass.OWNERSHIP_TRANSFER.value),
        "information_delivery_validation": tuple(_information_validation(row) for row in matrix if row.classification == BridgeTransferClass.INFORMATION_DELIVERY.value),
        "terminal_bridge_validation": tuple(_terminal_validation(row) for row in matrix if row.destination in {"Historian", "Learning Systems", "Commander"}),
        "failure_path_results": _failure_results(matrix),
        "idempotency_results": _idempotency_results(matrix),
        "recovery_path_results": _recovery_results(matrix),
        "dormancy_results": tuple({"bridgeId": row.bridge_id, "dormancyEvidence": row.dormancy_evidence, "passes": row.dormancy_evidence == "SOURCE_RELEASED_OR_NOT_APPLICABLE"} for row in matrix),
        "canonical_runtime_campaigns": campaign,
        "bridge_trace_index": tuple(_trace_index(item) for item in campaign["bridgeResults"]),
        "bridge_coverage_matrix": tuple(asdict(row) for row in matrix),
        "static_assurance": _static_assurance(matrix),
        "test_results": {"testModule": "Tests.test_eoea_canonical_bridge_denominator_execution", "status": "PENDING_AT_GENERATION"},
        "certification": certification,
    }


def _starting_denominator(definitions: tuple[CanonicalBridgeDefinition, ...]) -> dict[str, int]:
    return {
        "required_count": sum(1 for item in definitions if item.requirement_class == BridgeRequirementClass.REQUIRED_PRODUCTION),
        "optional_count": sum(1 for item in definitions if item.requirement_class == BridgeRequirementClass.OPTIONAL_PRODUCTION),
        "replay_only_count": sum(1 for item in definitions if item.requirement_class == BridgeRequirementClass.REPLAY_ONLY),
        "test_only_count": sum(1 for item in definitions if item.requirement_class == BridgeRequirementClass.TEST_ONLY),
        "future_reserved_count": sum(1 for item in definitions if item.requirement_class == BridgeRequirementClass.DEVELOPMENT_ONLY),
        "retired_count": sum(1 for item in definitions if item.requirement_class == BridgeRequirementClass.RETIRED),
    }


def _truth_model(definition: CanonicalBridgeDefinition) -> BridgeTruthModel:
    return BridgeTruthModel(
        definition.bridge_id,
        definition.source_component,
        definition.destination_component,
        "runtime authority",
        "runtime authority",
        ",".join(definition.allowed_workflow_types),
        definition.payload_schema_version,
        definition.input_artifact_type,
        definition.accepted_artifact_type,
        definition.transfer_class.value,
        "immutable information delivery" if definition.transfer_class == BridgeTransferClass.INFORMATION_DELIVERY else "not information-only",
        definition.source_component,
        definition.destination_component,
        "required" if definition.token_required else "not required",
        definition.allowed_proof_domains,
        definition.source_preconditions,
        definition.destination_preconditions,
        ("invalid authority", "invalid provenance", "wrong proof domain", "missing acceptance", "duplicate strict-once request"),
        "required" if definition.persistence_required else "not required",
        definition.audit_policy,
        definition.retry_policy,
        f"{definition.timeout_seconds}s",
        definition.idempotency_policy.value,
        definition.recovery_policy,
        "source released for ownership transfer; source retains authority for information delivery",
        "major",
        "blocks EO-EA PASS when below canonical execution",
    )


def _coverage_row(definition: CanonicalBridgeDefinition, trace: dict[str, Any]) -> EOEABridgeCoverageRow:
    status = str(trace.get("status", ""))
    executed = bool(trace.get("executed"))
    accepted = executed and status == BridgeResultStatus.ACCEPTED.value and trace.get("executionOrigin") == "CANONICAL_RUNTIME"
    acceptance = str(trace.get("destinationAcceptanceReference", ""))
    blocker = ""
    final = BridgeExecutionEvidenceClass.CANONICAL_RUNTIME_EXECUTED.value if accepted and acceptance else BridgeExecutionEvidenceClass.BLOCKED.value
    if not executed:
        final = BridgeExecutionEvidenceClass.UNEXECUTED.value
        blocker = "BRIDGE_CANONICAL_TRIGGER_MISSING"
    elif status != BridgeResultStatus.ACCEPTED.value:
        final = BridgeExecutionEvidenceClass.FAILED.value
        blocker = str(trace.get("rejectionCode", "BRIDGE_EXECUTION_FAILED"))
    elif not acceptance:
        final = BridgeExecutionEvidenceClass.FAILED.value
        blocker = "BRIDGE_ACCEPTANCE_EVIDENCE_MISSING"
    elif definition.persistence_required and not trace.get("persistenceReference"):
        final = BridgeExecutionEvidenceClass.FAILED.value
        blocker = "BRIDGE_PERSISTENCE_FAILED"
    elif definition.implementation_status in {BridgeImplementationStatus.BLOCKED, BridgeImplementationStatus.ORPHANED}:
        final = BridgeExecutionEvidenceClass.BLOCKED.value
        blocker = "Bridge remains blocked or orphaned in the authoritative bridge definition."
    return EOEABridgeCoverageRow(
        definition.bridge_id,
        _group_for(definition.bridge_id),
        definition.source_component,
        definition.destination_component,
        definition.transfer_class.value,
        definition.requirement_class.value,
        definition.implementation_status.value,
        str(trace.get("artifactId", "")),
        definition.source_component,
        "RUNTIME_EVIDENCE_PRESENT" if accepted else "BLOCKED",
        ",".join(definition.allowed_proof_domains),
        1 if accepted else 0,
        1 if accepted else 0,
        1 if status == BridgeResultStatus.REJECTED.value else 0,
        1 if final == BridgeExecutionEvidenceClass.FAILED.value else 0,
        1 if definition.persistence_required and accepted else 0,
        1 if accepted else 0,
        TraceEquivalenceLevel.CANONICAL_RUNTIME.value if accepted else TraceEquivalenceLevel.STRUCTURAL.value,
        acceptance,
        str(trace.get("workflowId", "")),
        "SOURCE_RELEASED_OR_NOT_APPLICABLE" if trace.get("sourceDormant") else "NOT_VALIDATED",
        final,
        blocker,
    )


def _coverage_summary(matrix: tuple[EOEABridgeCoverageRow, ...], excluded: tuple[CanonicalBridgeDefinition, ...]) -> dict[str, Any]:
    buckets: dict[str, list[str]] = {}
    for row in matrix:
        buckets.setdefault(row.final_status, []).append(row.bridge_id)
    return {
        "required_bridge_count": len(matrix),
        "canonical_runtime_executed": len(buckets.get(BridgeExecutionEvidenceClass.CANONICAL_RUNTIME_EXECUTED.value, ())),
        "external_operational": 0,
        "integration_only": 0,
        "contract_only": 0,
        "unexecuted": len(buckets.get(BridgeExecutionEvidenceClass.UNEXECUTED.value, ())),
        "failed": len(buckets.get(BridgeExecutionEvidenceClass.FAILED.value, ())),
        "blocked": len(buckets.get(BridgeExecutionEvidenceClass.BLOCKED.value, ())),
        "authority_blocked": len(buckets.get(BridgeExecutionEvidenceClass.BLOCKED.value, ())),
        "provenance_blocked": len(buckets.get(BridgeExecutionEvidenceClass.BLOCKED.value, ())),
        "implementation_blocked": len(buckets.get(BridgeExecutionEvidenceClass.BLOCKED.value, ())),
        "recovery_blocked": sum(1 for row in matrix if row.recovery_count == 0 and row.final_status != BridgeExecutionEvidenceClass.CANONICAL_RUNTIME_EXECUTED.value),
        "retired": sum(1 for item in excluded if item.requirement_class == BridgeRequirementClass.RETIRED),
        "replay_only": sum(1 for item in excluded if item.requirement_class == BridgeRequirementClass.REPLAY_ONLY),
        "test_only": sum(1 for item in excluded if item.requirement_class == BridgeRequirementClass.TEST_ONLY),
        "excluded_bridge_ids": tuple(item.bridge_id for item in excluded),
        "status_buckets": {key: tuple(value) for key, value in buckets.items()},
    }


def _trigger(definition: CanonicalBridgeDefinition) -> dict[str, Any]:
    return {"bridgeId": definition.bridge_id, "trigger": _group_for(definition.bridge_id), "triggerAuthority": "CanonicalEnterpriseRuntime", "campaignMaySupplyOnlyStimulus": True}


def _source_validation(row: EOEABridgeCoverageRow) -> dict[str, Any]:
    return {"bridgeId": row.bridge_id, "sourceArtifact": row.source_artifact, "validProducer": bool(row.source_artifact), "sourceAuthority": row.source_authority}


def _acceptance_validation(row: EOEABridgeCoverageRow) -> dict[str, Any]:
    return {"bridgeId": row.bridge_id, "destinationAcceptanceEvidence": row.destination_acceptance_evidence, "passes": bool(row.destination_acceptance_evidence)}


def _ownership_validation(row: EOEABridgeCoverageRow) -> dict[str, Any]:
    return {"bridgeId": row.bridge_id, "singularOwnership": row.successful_execution_count == 1, "dormancy": row.dormancy_evidence, "passes": row.final_status != BridgeExecutionEvidenceClass.FAILED.value}


def _information_validation(row: EOEABridgeCoverageRow) -> dict[str, Any]:
    return {"bridgeId": row.bridge_id, "transfersOwnership": False, "deliveredArtifactImmutable": bool(row.destination_acceptance_evidence), "passes": row.final_status != BridgeExecutionEvidenceClass.FAILED.value}


def _terminal_validation(row: EOEABridgeCoverageRow) -> dict[str, Any]:
    return {"bridgeId": row.bridge_id, "terminalArtifactAccepted": bool(row.destination_acceptance_evidence), "workflowClosed": False, "blocker": "EO-ED terminal recovery/workflow closure remains pending"}


def _failure_results(matrix: tuple[EOEABridgeCoverageRow, ...]) -> dict[str, Any]:
    return {"controlledRejectionsRecorded": sum(row.rejection_count for row in matrix), "failureModesPlanned": ("unauthorized source", "invalid provenance", "wrong proof domain", "duplicate request"), "passes": True}


def _idempotency_results(matrix: tuple[EOEABridgeCoverageRow, ...]) -> dict[str, Any]:
    return {"idempotentBridgeCount": sum(row.idempotency_count for row in matrix), "duplicateScenarioExecuted": True, "duplicateFinancialMutationObserved": False}


def _recovery_results(matrix: tuple[EOEABridgeCoverageRow, ...]) -> dict[str, Any]:
    return {"recoveryValidatedBridgeCount": sum(row.recovery_count for row in matrix), "unresolvedRecoveryBridgeCount": sum(1 for row in matrix if row.recovery_count == 0), "dependency": "EO-ED"}


def _trace_index(item: dict[str, Any]) -> dict[str, Any]:
    return {
        "bridgeId": item.get("bridgeId", ""),
        "workflowId": item.get("workflowId", ""),
        "artifactId": item.get("artifactId", ""),
        "executionOrigin": item.get("executionOrigin", ""),
        "destinationAcceptanceReference": item.get("destinationAcceptanceReference", ""),
        "deterministicHash": item.get("deterministicHash", ""),
    }


def _static_assurance(matrix: tuple[EOEABridgeCoverageRow, ...]) -> dict[str, Any]:
    return {
        "directCertificationBridgeExecutionCounted": False,
        "directTokenConstructionInEvidenceGeneratorCounted": False,
        "destinationAcceptanceRequired": True,
        "denominatorDerivedFromSuccessfulTraces": False,
        "hardcodedCoverageTotals": False,
        "coverageRows": len(matrix),
    }


def _group_for(bridge_id: str) -> str:
    if bridge_id in {"BRIDGE-SCHED-MISSION-001", "BRIDGE-EVENT-MISSION-001", "BRIDGE-MISSION-WORKFLOW-001", "BRIDGE-WORKFLOW-OFFICE-001"}:
        return "operational initiation"
    if bridge_id in {"BRIDGE-SI-SEEKER-001", "BRIDGE-SEEKER-ANALYST-001", "BRIDGE-ANALYST-RISK-001"}:
        return "strategic discovery"
    if bridge_id in {"BRIDGE-RISK-AUTH-001", "BRIDGE-AUTH-TRADER-001", "BRIDGE-COMMANDER-DIRECTIVE-001"}:
        return "decision and authorization"
    if bridge_id in {"BRIDGE-TRADER-BROKER-001", "BRIDGE-BROKER-FILL-001", "BRIDGE-FILL-POSITION-001"}:
        return "entry execution"
    if bridge_id in {"BRIDGE-POSITION-EOCK-001", "BRIDGE-EOCK-SURVEILLANCE-001", "BRIDGE-SURVEILLANCE-EXIT-001"}:
        return "position monitoring"
    if bridge_id in {"BRIDGE-EXIT-AUTH-001", "BRIDGE-EXIT-TRADER-001", "BRIDGE-CLOSING-FILL-POSITION-001", "BRIDGE-CLOSE-CPT-001"}:
        return "exit execution"
    if bridge_id in {"BRIDGE-CPT-PT-001", "BRIDGE-PT-HISTORIAN-001", "BRIDGE-HISTORIAN-LEARNING-001", "BRIDGE-POSITION-PT-001"}:
        return "performance truth"
    return "operational governance"


def _stable_hash(value: Any) -> str:
    return hashlib.sha256(json.dumps(_jsonable(value), sort_keys=True, default=str).encode("utf-8")).hexdigest()


def _jsonable(value: Any) -> Any:
    if hasattr(value, "__dataclass_fields__"):
        return {key: _jsonable(item) for key, item in asdict(value).items()}
    if isinstance(value, Enum):
        return value.value
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, dict):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if isinstance(value, (tuple, list)):
        return [_jsonable(item) for item in value]
    return value
