"""Verify the EO-001 ARGOS repository skeleton."""

from __future__ import annotations

from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]

REQUIRED_DIRECTORIES = [
    "0. Project Management",
    "1. Foundation",
    "2. Executive Group",
    "3. Seeker Group",
    "4. Analyst Group",
    "5. Risk Office",
    "6. Trader Group",
    "7. Historian Group",
    "8. Librarian Group",
    "9. Academy",
    "Tests",
    "Scripts",
    "Documentation",
    "ui",
    "ui/argos_control_panel",
    "src/argos",
    "src/argos/control_panel",
    "src/argos/foundation/audit",
    "src/argos/foundation/communication",
    "src/argos/foundation/configuration",
    "src/argos/foundation/contracts",
    "src/argos/foundation/identity",
    "src/argos/foundation/persistence",
    "src/argos/foundation/prompts",
    "src/argos/foundation/readiness",
    "src/argos/foundation/testing",
    "src/argos/foundation",
    "src/argos/executive",
    "src/argos/seeker",
    "src/argos/analyst",
    "src/argos/risk",
    "src/argos/trader",
    "src/argos/historian",
    "src/argos/librarian",
    "src/argos/academy",
]

REQUIRED_FILES = [
    "README.md",
    ".env.example",
    ".gitignore",
    "pyproject.toml",
    "Launch_ARGOS_Control_Panel.cmd",
    "0. Project Management/README.md",
    "1. Foundation/README.md",
    "2. Executive Group/README.md",
    "3. Seeker Group/README.md",
    "4. Analyst Group/README.md",
    "5. Risk Office/README.md",
    "6. Trader Group/README.md",
    "7. Historian Group/README.md",
    "8. Librarian Group/README.md",
    "9. Academy/README.md",
    "Tests/README.md",
    "Tests/test_audit_framework.py",
    "Tests/test_communication_framework.py",
    "Tests/test_configuration_framework.py",
    "Tests/test_contract_framework.py",
    "Tests/test_identity_framework.py",
    "Tests/test_persistence_framework.py",
    "Tests/test_prompt_specification_repository.py",
    "Tests/test_foundation_readiness.py",
    "Tests/test_foundation_testing_framework.py",
    "Tests/test_executive_framework.py",
    "Tests/test_commander_decision_engine.py",
    "Tests/test_executive_workflow.py",
    "Tests/test_chief_of_staff.py",
    "Tests/test_executive_dashboard.py",
    "Tests/test_treasury_trading_control_panel.py",
    "Tests/test_argos_control_panel_dashboard.py",
    "Tests/test_enterprise_command_center.py",
    "Tests/test_enterprise_activity_bus.py",
    "Tests/test_office_operating_modes_scheduler.py",
    "Tests/test_commander_notification_alert_center.py",
    "Tests/test_interactive_organization_explorer.py",
    "Tests/test_command_console.py",
    "Tests/test_infrastructure_resource_management.py",
    "Tests/test_live_portfolio_performance_console.py",
    "Tests/test_enterprise_credit_governor.py",
    "Tests/test_human_override.py",
    "Tests/test_executive_readiness.py",
    "Tests/test_seeker_department_framework.py",
    "Tests/test_technical_analysis_office.py",
    "Tests/test_fundamental_research_office.py",
    "Tests/test_macroeconomic_office.py",
    "Tests/test_news_sentiment_office.py",
    "Tests/test_options_flow_office.py",
    "Tests/test_cryptocurrency_office.py",
    "Tests/test_event_intelligence_office.py",
    "Tests/test_alternative_data_office.py",
    "Tests/test_fusion_office.py",
    "Tests/test_seeker_readiness.py",
    "Tests/test_analyst_department_framework.py",
    "Tests/test_statistical_analysis_office.py",
    "Tests/test_analyst_technical_analysis_office.py",
    "Tests/test_fundamental_analysis_office.py",
    "Tests/test_macroeconomic_analysis_office.py",
    "Tests/test_derivatives_analysis_office.py",
    "Tests/test_behavioral_analysis_office.py",
    "Tests/test_risk_interaction_office.py",
    "Tests/test_cross_discipline_review_office.py",
    "Tests/test_analytical_fusion_office.py",
    "Tests/test_analyst_readiness.py",
    "Tests/test_risk_office_framework.py",
    "Tests/test_position_risk_office.py",
    "Tests/test_portfolio_risk_office.py",
    "Tests/test_liquidity_risk_office.py",
    "Tests/test_volatility_risk_office.py",
    "Tests/test_tail_risk_office.py",
    "Tests/test_bubble_detection_office.py",
    "Tests/test_recovery_planning_office.py",
    "Tests/test_risk_fusion_office.py",
    "Tests/test_risk_readiness.py",
    "Tests/test_trader_group_framework.py",
    "Tests/test_trade_execution_office.py",
    "Tests/test_order_management_office.py",
    "Tests/test_broker_integration_office.py",
    "Tests/test_execution_quality_office.py",
    "Tests/test_position_management_office.py",
    "Tests/test_trade_monitoring_office.py",
    "Tests/test_trader_fusion_office.py",
    "Tests/test_trader_readiness.py",
    "Tests/test_historian_group_framework.py",
    "Tests/test_performance_measurement_office.py",
    "Tests/test_hypothesis_validation_office.py",
    "Tests/test_model_calibration_office.py",
    "Tests/test_prompt_evaluation_office.py",
    "Tests/test_decision_evaluation_office.py",
    "Tests/test_evidence_evaluation_office.py",
    "Tests/test_historian_fusion_office.py",
    "Tests/test_historian_readiness.py",
    "Tests/test_librarian_group_framework.py",
    "Tests/test_institutional_knowledge_office.py",
    "Tests/test_doctrine_management_office.py",
    "Tests/test_specification_repository_office.py",
    "Tests/test_knowledge_graph_office.py",
    "Tests/test_learning_integration_office.py",
    "Tests/test_librarian_fusion_office.py",
    "Tests/test_librarian_readiness.py",
    "Tests/test_academy_framework.py",
    "Tests/test_instruction_office.py",
    "Tests/test_curriculum_office.py",
    "Tests/test_knowledge_assessment_office.py",
    "Tests/test_case_study_office.py",
    "Tests/test_finance_tutor_office.py",
    "Tests/test_academy_fusion_office.py",
    "Tests/test_academy_readiness.py",
    "Scripts/README.md",
    "Scripts/start_argos_control_panel.py",
    "Scripts/launch_argos_control_panel.ps1",
    "Documentation/README.md",
    "Documentation/audit_traceability_framework.md",
    "Documentation/canonical_data_contract_framework.md",
    "Documentation/configuration_environment_framework.md",
    "Documentation/database_persistence_foundation.md",
    "Documentation/deterministic_communication_courier_framework.md",
    "Documentation/foundation_testing_framework.md",
    "Documentation/foundation_operational_readiness.md",
    "Documentation/identity_framework.md",
    "Documentation/prompt_specification_repository.md",
    "Documentation/executive_group_framework.md",
    "Documentation/commander_decision_engine.md",
    "Documentation/executive_workflow.md",
    "Documentation/chief_of_staff.md",
    "Documentation/executive_dashboard.md",
    "Documentation/treasury_trading_control_panel.md",
    "Documentation/argos_control_panel_dashboard.md",
    "Documentation/enterprise_command_center.md",
    "Documentation/enterprise_activity_bus.md",
    "Documentation/office_operating_modes_scheduling.md",
    "Documentation/commander_notification_alert_center.md",
    "Documentation/interactive_organization_explorer.md",
    "Documentation/command_console.md",
    "Documentation/infrastructure_ai_resource_management.md",
    "Documentation/live_portfolio_performance_console.md",
    "Documentation/enterprise_credit_governor.md",
    "Documentation/human_override_kill_switch.md",
    "Documentation/executive_operational_readiness.md",
    "Documentation/seeker_department_framework.md",
    "Documentation/technical_analysis_office.md",
    "Documentation/fundamental_research_office.md",
    "Documentation/macroeconomic_office.md",
    "Documentation/news_sentiment_office.md",
    "Documentation/options_flow_office.md",
    "Documentation/cryptocurrency_office.md",
    "Documentation/event_intelligence_office.md",
    "Documentation/alternative_data_office.md",
    "Documentation/fusion_office.md",
    "Documentation/seeker_operational_readiness.md",
    "Documentation/analyst_department_framework.md",
    "Documentation/statistical_analysis_office.md",
    "Documentation/analyst_technical_analysis_office.md",
    "Documentation/fundamental_analysis_office.md",
    "Documentation/macroeconomic_analysis_office.md",
    "Documentation/derivatives_analysis_office.md",
    "Documentation/behavioral_analysis_office.md",
    "Documentation/risk_interaction_office.md",
    "Documentation/cross_discipline_review_office.md",
    "Documentation/analytical_fusion_office.md",
    "Documentation/analyst_operational_readiness.md",
    "Documentation/risk_office_framework.md",
    "Documentation/position_risk_office.md",
    "Documentation/portfolio_risk_office.md",
    "Documentation/liquidity_risk_office.md",
    "Documentation/volatility_risk_office.md",
    "Documentation/tail_risk_office.md",
    "Documentation/bubble_detection_office.md",
    "Documentation/recovery_planning_office.md",
    "Documentation/risk_fusion_office.md",
    "Documentation/risk_operational_readiness.md",
    "Documentation/trader_group_framework.md",
    "Documentation/trade_execution_office.md",
    "Documentation/order_management_office.md",
    "Documentation/broker_integration_office.md",
    "Documentation/execution_quality_office.md",
    "Documentation/position_management_office.md",
    "Documentation/trade_monitoring_office.md",
    "Documentation/trader_fusion_office.md",
    "Documentation/trader_operational_readiness.md",
    "Documentation/historian_group_framework.md",
    "Documentation/performance_measurement_office.md",
    "Documentation/hypothesis_validation_office.md",
    "Documentation/model_calibration_office.md",
    "Documentation/prompt_evaluation_office.md",
    "Documentation/decision_evaluation_office.md",
    "Documentation/evidence_evaluation_office.md",
    "Documentation/historian_fusion_office.md",
    "Documentation/historian_operational_readiness.md",
    "Documentation/librarian_group_framework.md",
    "Documentation/institutional_knowledge_office.md",
    "Documentation/doctrine_management_office.md",
    "Documentation/specification_repository_office.md",
    "Documentation/knowledge_graph_office.md",
    "Documentation/learning_integration_office.md",
    "Documentation/librarian_fusion_office.md",
    "Documentation/librarian_operational_readiness.md",
    "Documentation/academy_framework.md",
    "Documentation/instruction_office.md",
    "Documentation/curriculum_office.md",
    "Documentation/knowledge_assessment_office.md",
    "Documentation/case_study_office.md",
    "Documentation/finance_tutor_office.md",
    "Documentation/academy_fusion_office.md",
    "Documentation/academy_operational_readiness.md",
    "src/argos/__init__.py",
    "src/argos/control_panel/__init__.py",
    "src/argos/control_panel/command_console.py",
    "src/argos/control_panel/cnac.py",
    "src/argos/control_panel/credit_governor.py",
    "src/argos/control_panel/eab.py",
    "src/argos/control_panel/ecc.py",
    "src/argos/control_panel/infrastructure.py",
    "src/argos/control_panel/ioe.py",
    "src/argos/control_panel/lppc.py",
    "src/argos/control_panel/runtime.py",
    "src/argos/control_panel/scheduler.py",
    "src/argos/control_panel/server.py",
    "src/argos/foundation/__init__.py",
    "src/argos/foundation/audit/__init__.py",
    "src/argos/foundation/audit/events.py",
    "src/argos/foundation/audit/log.py",
    "src/argos/foundation/audit/service.py",
    "src/argos/foundation/audit/trace.py",
    "src/argos/foundation/communication/__init__.py",
    "src/argos/foundation/communication/courier.py",
    "src/argos/foundation/communication/mailboxes.py",
    "src/argos/foundation/configuration/__init__.py",
    "src/argos/foundation/configuration/environment.py",
    "src/argos/foundation/configuration/service.py",
    "src/argos/foundation/contracts/__init__.py",
    "src/argos/foundation/contracts/base.py",
    "src/argos/foundation/identity/__init__.py",
    "src/argos/foundation/identity/identifiers.py",
    "src/argos/foundation/identity/registry.py",
    "src/argos/foundation/persistence/__init__.py",
    "src/argos/foundation/persistence/backup.py",
    "src/argos/foundation/persistence/migrations.py",
    "src/argos/foundation/persistence/records.py",
    "src/argos/foundation/persistence/repository.py",
    "src/argos/foundation/persistence/services.py",
    "src/argos/foundation/prompts/__init__.py",
    "src/argos/foundation/prompts/dependencies.py",
    "src/argos/foundation/prompts/prompts.py",
    "src/argos/foundation/prompts/specifications.py",
    "src/argos/foundation/readiness/__init__.py",
    "src/argos/foundation/readiness/reports.py",
    "src/argos/foundation/readiness/verifier.py",
    "src/argos/foundation/testing/__init__.py",
    "src/argos/foundation/testing/registry.py",
    "src/argos/foundation/testing/reports.py",
    "src/argos/foundation/testing/runner.py",
    "src/argos/executive/__init__.py",
    "src/argos/executive/briefing.py",
    "src/argos/executive/cdr.py",
    "src/argos/executive/chief_of_staff.py",
    "src/argos/executive/commander.py",
    "src/argos/executive/dashboard.py",
    "src/argos/executive/control_panel.py",
    "src/argos/executive/decisions.py",
    "src/argos/executive/engine.py",
    "src/argos/executive/mailboxes.py",
    "src/argos/executive/override.py",
    "src/argos/executive/readiness.py",
    "src/argos/executive/workflow.py",
    "src/argos/seeker/__init__.py",
    "src/argos/seeker/department.py",
    "src/argos/seeker/offices.py",
    "src/argos/seeker/technical.py",
    "src/argos/seeker/fundamental.py",
    "src/argos/seeker/macroeconomic.py",
    "src/argos/seeker/news_sentiment.py",
    "src/argos/seeker/options_flow.py",
    "src/argos/seeker/cryptocurrency.py",
    "src/argos/seeker/event_intelligence.py",
    "src/argos/seeker/alternative_data.py",
    "src/argos/seeker/fusion.py",
    "src/argos/seeker/readiness.py",
    "src/argos/analyst/department.py",
    "src/argos/analyst/offices.py",
    "src/argos/analyst/statistical.py",
    "src/argos/analyst/technical.py",
    "src/argos/analyst/fundamental.py",
    "src/argos/analyst/macroeconomic.py",
    "src/argos/analyst/derivatives.py",
    "src/argos/analyst/behavioral.py",
    "src/argos/analyst/risk_interaction.py",
    "src/argos/analyst/cross_discipline.py",
    "src/argos/analyst/analytical_fusion.py",
    "src/argos/analyst/readiness.py",
    "src/argos/analyst/__init__.py",
    "src/argos/risk/department.py",
    "src/argos/risk/offices.py",
    "src/argos/risk/position.py",
    "src/argos/risk/portfolio.py",
    "src/argos/risk/liquidity.py",
    "src/argos/risk/volatility.py",
    "src/argos/risk/tail.py",
    "src/argos/risk/bubble.py",
    "src/argos/risk/recovery.py",
    "src/argos/risk/fusion.py",
    "src/argos/risk/readiness.py",
    "src/argos/risk/__init__.py",
    "src/argos/trader/offices.py",
    "src/argos/trader/group.py",
    "src/argos/trader/trade_execution.py",
    "src/argos/trader/order_management.py",
    "src/argos/trader/broker_integration.py",
    "src/argos/trader/execution_quality.py",
    "src/argos/trader/position_management.py",
    "src/argos/trader/trade_monitoring.py",
    "src/argos/trader/fusion.py",
    "src/argos/trader/readiness.py",
    "src/argos/trader/__init__.py",
    "src/argos/historian/group.py",
    "src/argos/historian/performance.py",
    "src/argos/historian/hypothesis.py",
    "src/argos/historian/model_calibration.py",
    "src/argos/historian/prompt_evaluation.py",
    "src/argos/historian/decision_evaluation.py",
    "src/argos/historian/evidence_evaluation.py",
    "src/argos/historian/fusion.py",
    "src/argos/historian/readiness.py",
    "src/argos/historian/__init__.py",
    "src/argos/librarian/group.py",
    "src/argos/librarian/institutional_knowledge.py",
    "src/argos/librarian/doctrine_management.py",
    "src/argos/librarian/specification_repository.py",
    "src/argos/librarian/knowledge_graph.py",
    "src/argos/librarian/learning_integration.py",
    "src/argos/librarian/fusion.py",
    "src/argos/librarian/readiness.py",
    "src/argos/librarian/__init__.py",
    "src/argos/academy/framework.py",
    "src/argos/academy/instruction.py",
    "src/argos/academy/curriculum.py",
    "src/argos/academy/knowledge_assessment.py",
    "src/argos/academy/case_study.py",
    "src/argos/academy/finance_tutor.py",
    "src/argos/academy/fusion.py",
    "src/argos/academy/readiness.py",
    "src/argos/academy/__init__.py",
    "ui/argos_control_panel/index.html",
    "ui/argos_control_panel/styles.css",
    "ui/argos_control_panel/app.js",
]

PROHIBITED_EO001_FILES = [
    "src/argos/trader/broker.py",
    "src/argos/trader/execution.py",
    "src/argos/trader/live_trading.py",
]


def missing_directories(root: Path = REPOSITORY_ROOT) -> list[str]:
    """Return required directories that do not exist."""
    return [path for path in REQUIRED_DIRECTORIES if not (root / path).is_dir()]


def missing_files(root: Path = REPOSITORY_ROOT) -> list[str]:
    """Return required files that do not exist."""
    return [path for path in REQUIRED_FILES if not (root / path).is_file()]


def prohibited_files_present(root: Path = REPOSITORY_ROOT) -> list[str]:
    """Return EO-001-prohibited runtime trading files that exist."""
    return [path for path in PROHIBITED_EO001_FILES if (root / path).exists()]


def verify(root: Path = REPOSITORY_ROOT) -> list[str]:
    """Return a list of deterministic repository structure violations."""
    violations: list[str] = []
    violations.extend(f"Missing directory: {path}" for path in missing_directories(root))
    violations.extend(f"Missing file: {path}" for path in missing_files(root))
    violations.extend(f"Prohibited EO-001 file present: {path}" for path in prohibited_files_present(root))
    return violations


def main() -> int:
    violations = verify()
    if violations:
        print("ARGOS repository structure verification failed:")
        for violation in violations:
            print(f"- {violation}")
        return 1

    print("ARGOS repository structure verification passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
